from enum import Enum


class CallbackData(str, Enum):
    HOW_IT_WORKS = "HOW_IT_WORKS"
    MY_PROFILE = "MY_PROFILE"
    EDIT_DESCRIPTION = "EDIT_DESCRIPTION"
    EDIT_PHOTO = "EDIT_PHOTO"
    EDIT_SEX = "EDIT_SEX"
    EDIT_PREFERABLES = "EDIT_PREFERABLES"
    SEX_MALE = "SEX_MALE"
    SEX_FEMALE = "SEX_FEMALE"
    PREFERABLES_MALE = "PREFERABLES_MALE"
    PREFERABLES_FEMALE = "PREFERABLES_FEMALE"
    PREFERABLES_ALL = "PREFERABLES_ALL"
    SEE_PEOPLE = "SEE_PEOPLE"
    LIKE = "LIKE"
    DISLIKE = "DISLIKE"
    MY_MATCHES = "MY_MATCHES"
    ABOUT_CREATORS = "ABOUT_CREATORS"
    TO_MAIN_MENU = "TO_MAIN_MENU"

    DROP_PAIRS_AND_MATCHES = "DROP_PAIRS_AND_MATCHES"
